# Generated by Django 5.0.14 on 2026-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Mijoz ismi")),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="Telefon raqami"),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Qiziqayotgan xizmat yoki loyiha turi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("contacted", "Bog'lanildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Ariza holati",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Menejer izohi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kelib tushgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mijoz arizasi",
                "verbose_name_plural": "Mijozlar arizalari",
                "ordering": ["-created_at"],
            },
        ),
    ]
