# Generated by Django 5.0.14 on 2026-09-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Kategoriya nomi"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120,
                        unique=True,
                        verbose_name="Kategoriya slugi (URL uchun)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Kategoriya tavsifi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyiha kategoriyasi",
                "verbose_name_plural": "Loyiha kategoriyalari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Loyiha nomi")),
                (
                    "short_description",
                    models.TextField(
                        help_text="for cards/slider", verbose_name="Qisqa tavsif"
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        help_text="materials, execution",
                        verbose_name="Batafsil tavsif (materiallar va bajarilish bosqichlari)",
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        help_text="e.g. '450 kv.m'",
                        max_length=100,
                        verbose_name="Hajmi / Maydoni",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="e.g. 'Toshkent sh., Yunusobod'",
                        max_length=255,
                        verbose_name="Loyiha manzili / Joylashuvi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Jarayonda"),
                            ("completed", "Tugallangan"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Loyiha holati",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Tanlangan loyiha (Featured)?"
                    ),
                ),
                (
                    "show_in_hero",
                    models.BooleanField(
                        default=False,
                        help_text="Bosh sahifa slayderida ko'rsatish",
                        verbose_name="Bosh sahifa slayderida ko'rsatilsinmi?",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Full-size 1920x1080 banner",
                        null=True,
                        upload_to="projects/hero/",
                        verbose_name="Hero slayder rasmi (1920x1080)",
                    ),
                ),
                (
                    "main_thumbnail",
                    models.ImageField(
                        upload_to="projects/thumbnails/",
                        verbose_name="Asosiy miniatyura rasmi",
                    ),
                ),
                (
                    "before_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/before_after/",
                        verbose_name="Ta'mirdan oldingi rasm (Before)",
                    ),
                ),
                (
                    "after_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/before_after/",
                        verbose_name="Ta'mirdan keyingi rasm (After)",
                    ),
                ),
                (
                    "satellite_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/satellite/",
                        verbose_name="Sun'iy yo'ldosh xaritasi rasmi",
                    ),
                ),
                (
                    "satellite_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Sun'iy yo'ldosh yoki xarita havolasi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="projects.category",
                        verbose_name="Kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyiha",
                "verbose_name_plural": "Loyihalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/gallery/", verbose_name="Galereya rasmi"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Rasm izohi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yuklangan vaqt"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="projects.project",
                        verbose_name="Tegishli loyiha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loyiha galereya rasmi",
                "verbose_name_plural": "Loyiha galereya rasmlari",
                "ordering": ["id"],
            },
        ),
    ]
