# Generated by Django 5.0.14 on 2026-09-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1000000000.0,
                help_text="Loyihaning umumiy byudjeti yoki ajratilgan summa (default: 1.000.000.000)",
                max_digits=15,
                null=True,
                verbose_name="Loyihaga ajratilgan summa (so'm)",
            ),
        ),
    ]
