# Generated by Django 5.0.14 on 2026-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_phone",
                    models.CharField(
                        default="+998 90 123 45 67",
                        max_length=50,
                        verbose_name="Asosiy telefon raqami",
                    ),
                ),
                (
                    "secondary_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Qo'shimcha telefon raqami",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@merkuriy-r.uz",
                        max_length=254,
                        verbose_name="Rasmiy elektron pochta",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Toshkent shahri, Yunusobod tumani, Amir Temur shox ko'chasi",
                        max_length=255,
                        verbose_name="Ofis manzili",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        default="Dushanba - Shanba: 09:00 - 18:00",
                        max_length=100,
                        verbose_name="Ish vaqti",
                    ),
                ),
                (
                    "telegram_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Telegram havola"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Instagram havola"
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True, default="", verbose_name="Facebook havola"
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True, default="", verbose_name="YouTube havola"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aloqa ma'lumotlari",
                "verbose_name_plural": "Aloqa ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Merkuriy-R Xususiy qurilish firmasi",
                        max_length=255,
                        verbose_name="Kompaniya rasmiy nomi",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="Biz haqimizda",
                        max_length=255,
                        verbose_name="Biz haqimizda sarlavhasi",
                    ),
                ),
                (
                    "about_description",
                    models.TextField(
                        blank=True,
                        default="Merkuriy-R xususiy qurilish firmasi ko'p yillik tajribaga ega bo'lib, turar-joy va tijoriy binolarni loyihalash, qurish va ta'mirlash ishlarini yuqori sifat standartlari asosida amalga oshiradi.",
                        verbose_name="Biz haqimizda batafsil tavsif",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Yillik tajriba"
                    ),
                ),
                (
                    "completed_projects",
                    models.PositiveIntegerField(
                        default=150, verbose_name="Tugallangan loyihalar soni"
                    ),
                ),
                (
                    "master_workers",
                    models.PositiveIntegerField(
                        default=45, verbose_name="Mutaxassis ishchilar soni"
                    ),
                ),
                (
                    "promo_active",
                    models.BooleanField(
                        default=False, verbose_name="Aksiya banneri faolmi?"
                    ),
                ),
                (
                    "promo_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Aksiya sarlavhasi",
                    ),
                ),
                (
                    "promo_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Aksiya tavsifi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sayt asosiy sozlamalari",
                "verbose_name_plural": "Sayt asosiy sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=150, verbose_name="Mijoz ismi"),
                ),
                (
                    "client_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Lavozimi / Faoliyat sohasi / Tashkilot",
                    ),
                ),
                ("quote", models.TextField(verbose_name="Mijoz fikri / Izoh")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Mijoz fotosurati",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 yulduz"),
                            (2, "2 yulduz"),
                            (3, "3 yulduz"),
                            (4, "4 yulduz"),
                            (5, "5 yulduz"),
                        ],
                        default=5,
                        verbose_name="Baho (1-5)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Saytda ko'rsatilsinmi?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Qo'shilgan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mijoz fikri",
                "verbose_name_plural": "Mijozlar fikrlari",
                "ordering": ["-created_at"],
            },
        ),
    ]
